### PR TITLE
add catalog query interface

### PR DESCRIPTION
**Pull request by mqshen**
add catalog query interface that return total count of services.

### CODE REVIEW

**Review by sanxun0325 — COMMENTED** [review]
use GetAllServicesInfo you can get all the services
https://github.com/nacos-group/nacos-sdk-go/blob/master/clients/naming_client/naming_client.go#L194

**Comment by mqshen** [comment]
this api not return total count of all services.

**Comment by sanxun0325** [comment]
> 



> this api not return total count of all services.

count is all services num

**Comment by mqshen** [comment]
> 

count is size of return Doms. not the all services.

**Pull request closed without merging**
