### PR TITLE
Add function UpdateInstance() #286

### LINKED ISSUE #286: Add function UpdateInstance()
Instance had RegisterInstance() and DeregisterInstance() currently. 
Function UpdateInstance() is useful for updating workload information, so client could choose the right instance.

### PR DESCRIPTION
**Pull request by yangyanqing**
close #286

### CODE REVIEW

**Review by sanxun0325 — COMMENTED** [review]
You can split pr so that the current PR is just the code associated with updateInstance。

**Comment by yangyanqing** [comment]
1. Code style fix was remove
2. Add `RemoveBeatInfo()` and `AddBeatInfo()` in UpdateInstance(), so beat can send the LAST data to Nacos
3. Unittest `Test_UpdateServiceInstance_withoutGroupName` was unstable because `PUT /nacos/v1/ns/instance/beat` was called by go routine.

**Review by sanxun0325 — COMMENTED** [review]
Try to fix the unit tests: https://github.com/nacos-group/nacos-sdk-go/pull/287/checks#step:5:227

**Review by sanxun0325 — APPROVED** [review]
LGTM

**Pull request merged**
