### PR TITLE
[#476 feature: add support tenant to client query]

### PR DESCRIPTION
**Pull request by lishuo5263**
### Feature
* Add cache param Tenant
* Support client use namespace to query Instance

### CODE REVIEW

**Review by sanxun0325 — COMMENTED** [review]
Why add tenant? query by NamespaceID is already available

**Comment by lishuo5263** [comment]
> Why add tenant? query by NamespaceID is already available
I can't upload the screen short, i will send mail talk with you,and explain reason.

**Comment by sanxun0325** [comment]
image
each namespce id corresponds to a client. The service map in the client cache service instances under the current namespace

**Comment by sanxun0325** [comment]
If you only want to query the instance list based on the namespace ID, refer: https://github.com/nacos-group/nacos-sdk-go/blob/master/example/service/main.go#L271

**Comment by lishuo5263** [comment]
> If you only want to query the instance list based on the namespace ID, refer: https://github.com/nacos-group/nacos-sdk-go/blob/master/example/service/main.go#L271

Em.. I thought the cc should be support entire namespace to query,not like ony bind one namespace to use.

**Comment by lishuo5263** [comment]
> If you only want to query the instance list based on the namespace ID, refer: https://github.com/nacos-group/nacos-sdk-go/blob/master/example/service/main.go#L271

Em.. I thought the cc should be support entire namespace to query,not like ony bind one namespace to use.

**Comment by sanxun0325** [comment]
> 

don't need to do this; GetServiceList supports passing namespaceID

**Pull request closed without merging**
