### PR TITLE
[ISSUE #232] add the test in remote package

### PR DESCRIPTION
**Pull request by brotherlu-xcq**
add the test file in remote package.

### CODE REVIEW

**Review by sanxun0325 — CHANGES_REQUESTED** [review]
There are a lot of functions to test in the RPC package, can you cover more?

**Comment by brotherlu-xcq** [comment]
@sanxun0325 Yes, of course. but I am newbie in golang. I am not sure how to mock the grpc response in test file. could you give me some advice?

**Comment by sanxun0325** [comment]
> @sanxun0325 Yes, of course. but I am newbie in golang. I am not sure how to mock the grpc response in test file. could you give me some advice?

I will submit some ut later for your reference

**Comment by brotherlu-xcq** [comment]
thank you so much.

**Pull request closed without merging**
